package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * Cartao generated by hbm2java
 */
public class Cartao  implements java.io.Serializable {


     private int codcartao;
     private long pontos;
     private int idcliente;

    public Cartao() {
    }

    public Cartao(int codcartao, long pontos, int idcliente) {
       this.codcartao = codcartao;
       this.pontos = pontos;
       this.idcliente = idcliente;
    }
   
    public int getCodcartao() {
        return this.codcartao;
    }
    
    public void setCodcartao(int codcartao) {
        this.codcartao = codcartao;
    }
    public long getPontos() {
        return this.pontos;
    }
    
    public void setPontos(long pontos) {
        this.pontos = pontos;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }




}


