package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idcliente;
     private String nome;
     private String morada;
     private int contacto;
     private int nif;

    public Cliente() {
    }

    public Cliente(int idcliente, String nome, String morada, int contacto, int nif) {
       this.idcliente = idcliente;
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
       this.nif = nif;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }
    public int getNif() {
        return this.nif;
    }
    
    public void setNif(int nif) {
        this.nif = nif;
    }




}


