package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Desconto generated by hbm2java
 */
public class Desconto  implements java.io.Serializable {


     private int iddesconto;
     private int idproduto;
     private BigDecimal vlrdesconto;

    public Desconto() {
    }

    public Desconto(int iddesconto, int idproduto, BigDecimal vlrdesconto) {
       this.iddesconto = iddesconto;
       this.idproduto = idproduto;
       this.vlrdesconto = vlrdesconto;
    }
   
    public int getIddesconto() {
        return this.iddesconto;
    }
    
    public void setIddesconto(int iddesconto) {
        this.iddesconto = iddesconto;
    }
    public int getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(int idproduto) {
        this.idproduto = idproduto;
    }
    public BigDecimal getVlrdesconto() {
        return this.vlrdesconto;
    }
    
    public void setVlrdesconto(BigDecimal vlrdesconto) {
        this.vlrdesconto = vlrdesconto;
    }




}


