package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalhepedido generated by hbm2java
 */
public class Detalhepedido  implements java.io.Serializable {


     private long nlinha;
     private int codpedido;
     private int idproduto;
     private Long qtd;
     private BigDecimal vlrunit;

    public Detalhepedido() {
    }

	
    public Detalhepedido(long nlinha, int codpedido, int idproduto) {
        this.nlinha = nlinha;
        this.codpedido = codpedido;
        this.idproduto = idproduto;
    }
    public Detalhepedido(long nlinha, int codpedido, int idproduto, Long qtd, BigDecimal vlrunit) {
       this.nlinha = nlinha;
       this.codpedido = codpedido;
       this.idproduto = idproduto;
       this.qtd = qtd;
       this.vlrunit = vlrunit;
    }
   
    public long getNlinha() {
        return this.nlinha;
    }
    
    public void setNlinha(long nlinha) {
        this.nlinha = nlinha;
    }
    public int getCodpedido() {
        return this.codpedido;
    }
    
    public void setCodpedido(int codpedido) {
        this.codpedido = codpedido;
    }
    public int getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(int idproduto) {
        this.idproduto = idproduto;
    }
    public Long getQtd() {
        return this.qtd;
    }
    
    public void setQtd(Long qtd) {
        this.qtd = qtd;
    }
    public BigDecimal getVlrunit() {
        return this.vlrunit;
    }
    
    public void setVlrunit(BigDecimal vlrunit) {
        this.vlrunit = vlrunit;
    }




}


