package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Encomenda generated by hbm2java
 */
public class Encomenda  implements java.io.Serializable {


     private int idencomenda;
     private int idfornecedor;
     private Date data;
     private BigDecimal vlrtotal;

    public Encomenda() {
    }

    public Encomenda(int idencomenda, int idfornecedor, Date data, BigDecimal vlrtotal) {
       this.idencomenda = idencomenda;
       this.idfornecedor = idfornecedor;
       this.data = data;
       this.vlrtotal = vlrtotal;
    }
   
    public int getIdencomenda() {
        return this.idencomenda;
    }
    
    public void setIdencomenda(int idencomenda) {
        this.idencomenda = idencomenda;
    }
    public int getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(int idfornecedor) {
        this.idfornecedor = idfornecedor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public BigDecimal getVlrtotal() {
        return this.vlrtotal;
    }
    
    public void setVlrtotal(BigDecimal vlrtotal) {
        this.vlrtotal = vlrtotal;
    }




}


