package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * EncomendaProdutoId generated by hbm2java
 */
public class EncomendaProdutoId  implements java.io.Serializable {


     private int idencomenda;
     private int idproduto;
     private long linhaencomenda;

    public EncomendaProdutoId() {
    }

    public EncomendaProdutoId(int idencomenda, int idproduto, long linhaencomenda) {
       this.idencomenda = idencomenda;
       this.idproduto = idproduto;
       this.linhaencomenda = linhaencomenda;
    }
   
    public int getIdencomenda() {
        return this.idencomenda;
    }
    
    public void setIdencomenda(int idencomenda) {
        this.idencomenda = idencomenda;
    }
    public int getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(int idproduto) {
        this.idproduto = idproduto;
    }
    public long getLinhaencomenda() {
        return this.linhaencomenda;
    }
    
    public void setLinhaencomenda(long linhaencomenda) {
        this.linhaencomenda = linhaencomenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EncomendaProdutoId) ) return false;
		 EncomendaProdutoId castOther = ( EncomendaProdutoId ) other; 
         
		 return (this.getIdencomenda()==castOther.getIdencomenda())
 && (this.getIdproduto()==castOther.getIdproduto())
 && (this.getLinhaencomenda()==castOther.getLinhaencomenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdencomenda();
         result = 37 * result + this.getIdproduto();
         result = 37 * result + (int) this.getLinhaencomenda();
         return result;
   }   


}


