package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int idfornecedor;
     private String nome;
     private String morada;
     private int contacto;

    public Fornecedor() {
    }

    public Fornecedor(int idfornecedor, String nome, String morada, int contacto) {
       this.idfornecedor = idfornecedor;
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
    }
   
    public int getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(int idfornecedor) {
        this.idfornecedor = idfornecedor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }




}


