package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int idfuncionario;
     private String nome;
     private String morada;
     private int contacto;

    public Funcionario() {
    }

    public Funcionario(int idfuncionario, String nome, String morada, int contacto) {
       this.idfuncionario = idfuncionario;
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
    }
   
    public int getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }




}


