package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento  implements java.io.Serializable {


     private PagamentoId id;
     private BigDecimal valor;

    public Pagamento() {
    }

    public Pagamento(PagamentoId id, BigDecimal valor) {
       this.id = id;
       this.valor = valor;
    }
   
    public PagamentoId getId() {
        return this.id;
    }
    
    public void setId(PagamentoId id) {
        this.id = id;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


