package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int codpedido;
     private int idcliente;
     private Integer idfuncionario;
     private BigDecimal valor;
     private Date data;

    public Pedido() {
    }

	
    public Pedido(int codpedido, int idcliente, BigDecimal valor, Date data) {
        this.codpedido = codpedido;
        this.idcliente = idcliente;
        this.valor = valor;
        this.data = data;
    }
    public Pedido(int codpedido, int idcliente, Integer idfuncionario, BigDecimal valor, Date data) {
       this.codpedido = codpedido;
       this.idcliente = idcliente;
       this.idfuncionario = idfuncionario;
       this.valor = valor;
       this.data = data;
    }
   
    public int getCodpedido() {
        return this.codpedido;
    }
    
    public void setCodpedido(int codpedido) {
        this.codpedido = codpedido;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public Integer getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(Integer idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


