package dao;
// Generated 28/mai/2018 15:27:08 by Hibernate Tools 4.3.1



/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idproduto;
     private String desigproduto;
     private long vlrunit;
     private short unistock;

    public Produto() {
    }

    public Produto(int idproduto, String desigproduto, long vlrunit, short unistock) {
       this.idproduto = idproduto;
       this.desigproduto = desigproduto;
       this.vlrunit = vlrunit;
       this.unistock = unistock;
    }
   
    public int getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(int idproduto) {
        this.idproduto = idproduto;
    }
    public String getDesigproduto() {
        return this.desigproduto;
    }
    
    public void setDesigproduto(String desigproduto) {
        this.desigproduto = desigproduto;
    }
    public long getVlrunit() {
        return this.vlrunit;
    }
    
    public void setVlrunit(long vlrunit) {
        this.vlrunit = vlrunit;
    }
    public short getUnistock() {
        return this.unistock;
    }
    
    public void setUnistock(short unistock) {
        this.unistock = unistock;
    }




}


